# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6c690acb836e7a4e93e8c722b46a731"
name = "orders-dashboardb"
application_url = "https://melodious-spirit-production-897f.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
topics = [ "orders/updated" ]
uri = "/webhooks/orders/updated"

[[webhooks.subscriptions]]
topics = [ "orders/cancelled" ]
uri = "/webhooks/orders/cancelled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://melodious-spirit-production-897f.up.railway.app/auth/callback"
]
